### ISSUE TITLE
How to switch on/off the mailbox LED?

### ISSUE THREAD

**Issue by probonopd** [bsmulders/cx300-control#3]
The key "1" has a built-in mailbox LED (as is mentioned in https://www.youtube.com/watch?v=zMXqXTZBhSw). I did not yet find out how this can be switched. Do you know?

**Comment by bsmulders** [comment]
I don't have this LED on my device so I can't help out. My suggestion is to try different numbers in a similar way as the speaker-phone LED.

**Comment by OE4AMW** [comment]
Add 0x02 to the byte that switches"mute mic" to turn the LED on.

See also https://github.com/OE4AMW/cx300-control/commit/3c51306d7051a94d6a52ed336b376ee61027847e  - it also adds some color-combinations in the Status LEDs (found using brute force).

**Comment by probonopd** [comment]
Thank you very much @OE4AMW.
